### ISSUE TITLE
Todo edit and delete options.

### ISSUE THREAD

**Issue by Tolsee** [Tolsee/graphql-to-do#2]
- [ ] Add edit pop-up in the client.
- [ ] Add delete support in the server.
- [ ] Add delete confirm in client.
